package main

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema

import (
	"fmt"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {

	err := entc.Generate("./internal/entities", &gen.Config{
		Header:  "// Code generated by ent, DO NOT EDIT.",
		Target:  "./internal/ent",
		Package: "panel.go/internal/ent",
	})
	if err != nil {
		panic(fmt.Sprintf("failed generating ent: %v", err))
	}

}
